name: Validate Composer.json

on:
  push:
    paths:
      - "composer.json"
  pull_request:
    paths:
      - "composer.json"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Validate composer.json
        run: composer validate --no-check-lock

      - name: Install dependencies
        run: composer require --dev phpunit/phpunit --no-update

      - name: Install dependencies from lock file
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Extract coverage percentage
        run: |
          COVERAGE=$(vendor/bin/phpunit --coverage-text | grep -Po 'Lines:\s*\K[0-9]+\.[0-9]+')
          echo "coverage=$COVERAGE%" >> $GITHUB_ENV

      - name: Generate coverage badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'Test coverage'
          status: ${{ env.coverage }}
          color: 'blue,555,daf'
          path: '.github/badges/coverage.svg'
